<?php  //[STAMP] d06113ff5f1983c1e6daa0221f47739c
namespace SprykerSdkTest\AsyncApi\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait AsyncApiTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
